/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { HazardousFactor, HazardCategory, RiskLevel } from "./types";

export const DEFAULT_HAZARDOUS_FACTORS: HazardousFactor[] = [
  {
    id: "1",
    manageNo: "HAZ-CHEM-001",
    nameKo: "벤젠",
    nameEn: "Benzene",
    casNo: "71-43-2",
    category: HazardCategory.CHEMICAL,
    department: "품질관리부",
    process: "화학 정밀 분석 공정",
    exposureLimitTwa: "0.5 ppm",
    exposureLimitStel: "2.5 ppm",
    healthEffects: "발암성(백혈병), 혈액장애(빈혈, 백혈구 감소), 피부 자극, 흡입 시 중추신경계 억제 및 어지러움 유발.",
    msdsLink: "MSDS-CHEM-71432",
    ppeRequired: ["송기마스크 (또는 유기화합물용 방독마스크 1급)", "내화학성 보안경", "내화학성 장갑 (니트릴/바이톤)", "불침투성 전신 보호의"],
    safetyRules: "1. 작업 전 국소배기장치 가동 상태를 반드시 확인하십시오.\n2. 밀폐형 분석 챔버(Fume Hood) 내부에서만 취급하십시오.\n3. 취급 중 금연 및 인화성 물질과의 접촉을 전면 금지합니다.\n4. 정기적으로 작업장 내 가스 농도를 측정하십시오.",
    emergencyRules: "1. 흡입 시 즉시 신선한 공기가 있는 곳으로 대피시키고 필요 시 인공호흡을 실시하십시오.\n2. 피부 접촉 시 오염된 옷을 벗고 다량의 물과 비누로 최소 15분 이상 씻어내십시오.\n3. 누출 시 소화기 비치 하에 흡착포를 이용하여 회수하고 밀폐 용기에 격리하십시오.",
    measurementInterval: "6개월 1회",
    specialExam: true,
    detailedSafetyDiagnostic: true,
    workEnvMeasurement: true,
    riskLevel: RiskLevel.HIGH,
    ghsPictograms: ["flammable", "toxic", "health_hazard", "irritant"],
    createdAt: "2026-01-10T09:00:00Z",
  },
  {
    id: "2",
    manageNo: "HAZ-CHEM-002",
    nameKo: "톨루엔",
    nameEn: "Toluene",
    casNo: "108-88-3",
    category: HazardCategory.CHEMICAL,
    department: "생산기술부",
    process: "금속 표면 도장 및 세척 공정",
    exposureLimitTwa: "50 ppm",
    exposureLimitStel: "150 ppm",
    healthEffects: "두통, 어지러움, 피로, 중추신경계 저하, 고농도 노출 시 환각 및 의식 상실, 장기 노출 시 생식독성 유발 가능.",
    msdsLink: "MSDS-CHEM-108883",
    ppeRequired: ["유기용제용 방독마스크", "보안경", "내용제성 장갑 (부틸고무 또는 니트릴)"],
    safetyRules: "1. 유기용제 보관 창고는 항시 25도 이하로 유지하고 환풍기를 작동하십시오.\n2. 세척조 가동 시 국소배기장치를 '강'으로 설정하십시오.\n3. 스파크가 발생할 수 있는 철제 도구의 마찰을 금지합니다.\n4. 정전기 방지용 안전화를 착용하십시오.",
    emergencyRules: "1. 누출 시 점화원을 즉시 제거하고 질소나 비활성 물질로 덮어 확산을 방지하십시오.\n2. 눈에 들어갔을 경우 즉시 흐르는 물로 눈꺼풀을 들어 올려 15분 이상 씻어낸 후 의사의 진료를 받으십시오.",
    measurementInterval: "6개월 1회",
    specialExam: true,
    detailedSafetyDiagnostic: true,
    workEnvMeasurement: true,
    riskLevel: RiskLevel.MEDIUM,
    ghsPictograms: ["flammable", "health_hazard", "irritant"],
    createdAt: "2026-02-15T10:30:00Z",
  },
  {
    id: "3",
    manageNo: "HAZ-CHEM-003",
    nameKo: "포름알데히드",
    nameEn: "Formaldehyde",
    casNo: "50-00-0",
    category: HazardCategory.CHEMICAL,
    department: "연구개발소",
    process: "조직 고정 및 샘플 보존 공정",
    exposureLimitTwa: "0.3 ppm",
    exposureLimitStel: "0.5 ppm (Ceiling)",
    healthEffects: "인체 발암성 물질(분류 1급), 피부 과민성(알레르기), 눈 및 호흡기계 자극, 흡입 시 천식 및 만성 기관지염 유발 가능.",
    msdsLink: "MSDS-CHEM-50000",
    ppeRequired: ["정밀 화합물용 방독마스크 (유기/산성용)", "안면보호구 (Face Shield)", "내화학성 장갑 (네오프렌)", "실험실용 보호 가운"],
    safetyRules: "1. 가스 감지 밸브가 정상 작동 중인지 정기 점검하십시오.\n2. 밀폐 시약장 내부 보관 및 이중 용기 포장을 유지하십시오.\n3. 희석액 조제 시 반드시 흄후드 스노클 후드를 근접 배치하여 작업하십시오.",
    emergencyRules: "1. 다량 누출 시 즉시 대피 경보를 발령하고 소방서에 신고하십시오.\n2. 피부 오염 부위는 생리식염수 또는 물로 세척하고 화상 전문 병원으로 이송하십시오.\n3. 오염 지역의 공기는 양압식 호흡기를 착용한 요원만 진입하여 강제 환기 처리하십시오.",
    measurementInterval: "6개월 1회",
    specialExam: true,
    detailedSafetyDiagnostic: true,
    workEnvMeasurement: true,
    riskLevel: RiskLevel.HIGH,
    ghsPictograms: ["toxic", "corrosive", "health_hazard", "irritant"],
    createdAt: "2026-03-01T14:15:00Z",
  },
  {
    id: "4",
    manageNo: "HAZ-PHYS-001",
    nameKo: "소음 (90dB 이상)",
    nameEn: "Occupational Noise",
    category: HazardCategory.PHYSICAL,
    department: "프레스가공부",
    process: "금속 고속 타공 및 절단 공정",
    exposureLimitTwa: "90 dBA (8시간 기준)",
    healthEffects: "소음성 난청(영구적 청력 손실), 이명, 수면 장애, 심혈관계 영향 및 극도의 직무 스트레스 유발.",
    msdsLink: "N/A (물리적 인자)",
    ppeRequired: ["차음 귀덮개 (Earmuffs, NRR 25dB 이상)", "폼 타입 귀마개 (Earplugs)"],
    safetyRules: "1. 소음 발생 장비 주변에 노란색 청력보호구 의무착용 표지판을 게시하십시오.\n2. 프레스 가동 중에는 기기 방음커버를 완전히 닫아두십시오.\n3. 교대 조 편성을 통해 인당 고소음 노출 누적 시간을 하루 4시간 미만으로 제한하십시오.",
    emergencyRules: "1. 돌발성 고음(폭발음 등) 노출 시 즉시 작업자가 보호구를 착용하고 대피하여 외이도 손상 여부를 청력 검사로 확인하십시오.",
    measurementInterval: "6개월 1회",
    specialExam: true,
    detailedSafetyDiagnostic: false,
    workEnvMeasurement: true,
    riskLevel: RiskLevel.MEDIUM,
    ghsPictograms: [],
    createdAt: "2026-01-20T11:00:00Z",
  },
  {
    id: "5",
    manageNo: "HAZ-CHEM-004",
    nameKo: "이소프로필알코올 (IPA)",
    nameEn: "Isopropyl Alcohol",
    casNo: "67-63-0",
    category: HazardCategory.CHEMICAL,
    department: "완제품포장부",
    process: "출고 전 표면 오염 세척 및 소독",
    exposureLimitTwa: "200 ppm",
    exposureLimitStel: "400 ppm",
    healthEffects: "증기 흡입 시 가벼운 두통, 졸음, 점막 및 눈 자극, 장기 노출 시 피부 건조 및 갈라짐 유발.",
    msdsLink: "MSDS-CHEM-67630",
    ppeRequired: ["유기용제용 방독마스크 (필요 시 방진방독 겸용)", "밀착형 방진방독 고글", "니트릴 장갑"],
    safetyRules: "1. 세척제 스프레이 분사 시 국소배기장치 흡입구 방향을 확인하십시오.\n2. 보관 용기는 사용 후 반드시 뚜껑을 밀폐하십시오.\n3. 정전기 불꽃 발생을 예방하기 위해 도포 장비 접지 상태를 확인하십시오.",
    emergencyRules: "1. 눈 접촉 시 다량의 물로 눈 안쪽에서 바깥쪽으로 부드럽게 세척하십시오.\n2. 오용 시 토하게 하지 말고 다량의 물을 마시게 한 뒤 즉시 의사의 지시를 받으십시오.",
    measurementInterval: "6개월 1회",
    specialExam: true,
    detailedSafetyDiagnostic: false,
    workEnvMeasurement: true,
    riskLevel: RiskLevel.LOW,
    ghsPictograms: ["flammable", "irritant"],
    createdAt: "2026-04-10T16:00:00Z",
  },
  {
    id: "6",
    manageNo: "HAZ-ERGO-001",
    nameKo: "인력 중량물 취급 및 반복 작업",
    nameEn: "Repetitive Lifting & Manual Handling",
    category: HazardCategory.ERGONOMIC,
    department: "자재물류팀",
    process: "원자재 보관 및 박스 팔레트 적재",
    exposureLimitTwa: "여성 15kg / 남성 25kg 이하 (단발성 제한)",
    healthEffects: "요추염좌, 추간판 탈출증(디스크), 회전근개 파열 등 근골격계 질환(MSDs), 만성 허리 통증.",
    msdsLink: "N/A (인간공학적 요인)",
    ppeRequired: ["요추 지지대 (허리보호대)", "안전화 (스틸토 적용)", "미끄럼 방지 고무코팅 장갑"],
    safetyRules: "1. 중량물 인양 시 허리를 굽히지 말고 무릎을 굽혀 다리 힘으로 일어나십시오.\n2. 박스 적재 시 무게중심을 몸에 최대한 밀착시켜 이동하십시오.\n3. 1시간 연속 적재 작업 후 반드시 10분간 요추 스트레칭 휴식 시간을 보장하십시오.\n4. 20kg 이상의 무거운 자재는 2인 1조 작업 또는 호이스트/대차를 사용하십시오.",
    emergencyRules: "1. 급성 요부 염좌 발생 시 즉시 인양 작업을 중단시키고, 침상 안정을 취하게 한 후 아이스팩 찜질 및 정형외과 진료를 연계하십시오.",
    measurementInterval: "3년 1회 (근골격계 유해요인조사)",
    specialExam: false,
    detailedSafetyDiagnostic: false,
    workEnvMeasurement: false,
    riskLevel: RiskLevel.MEDIUM,
    ghsPictograms: [],
    createdAt: "2026-05-02T13:40:00Z",
  }
];
